### ISSUE TITLE
Unable to deploy via big-iq

### ISSUE THREAD

**Issue by Zjemm** [F5Networks/f5-ansible-bigip#13]
Hi, I have tested this new ansible v2 version, but ran into issue's talking to big-iq.
When talking towards the big-ip, it seems to work ok, but to big-iq it does not.

I can deploy and patch via the API, using ansible or PHP. And using the old ATC module found on devcentral GitHub (= also API)

But using the same json file with the new module towards big-iq, i can't get it to work.
so for now i’m using the normal API functionality in ansible to talk to the big-iq

with the files (playbook and json decleration ) beneath, i get the following message:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "{'code': 422, 'message': 'status:422, body:{\"code\":422,\"message\":\"Invalid request value \\'[object Object]\\' (path: /declaration) : should have required property \\'class\\' {\\\\\"missingProperty\\\\\":\\\\\"class\\\\\"}\"}', 'originalRequestBody': '{\"code\":422,\"message\":\"Invalid request value \\'[object Object]\\' (path: /declaration) : should have required property \\'class\\' {\\\\\"missingProperty\\\\\":\\\\\"class\\\\\"}\"}', 'referer': '10.10.0.xxx', 'restOperationId': 57963195, 'errorStack': [], 'kind': ':resterrorresponse'}"}`

i’m deploying from ansible to big-iq which will then go to the target big-ip
exactly the same json file, does work when using an api call (and it does not matter if i’m doing the api call from ansible of from a php script or even from within vscode)

so somehow, the v2 ansible module, is expecting a different json format? but i can’t figure out, what it is.

do you have any clue? or could there be a fault in the big-iq module part of the plugin?

stripping out the application name at the top, and the target part, makes me able to push this json file using the v2 ansible module to the big-IP.
so it’s only big-IQ related

please let me know your thoughts

```
- hosts: all
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: "10.10.0.xxx"
    ansible_user: "admin"
    ansible_httpapi_password: "xxxxx"
    ansible_network_os: f5networks.f5_bigip.bigiq
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Declaration test
      bigiq_as3_deploy:
        content: "{{ lookup('file', '1.json') }}"
        #service_type: "as3"
```

```
{
"applicationName": "O-E",
"appSvcsDeclaration": {
    "class": "AS3",
    "action": "deploy",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.31.0",
        "target": {
            "address": "10.10.0.xxx"
        },
        "pco": {
            "class": "Tenant",
            "vip1_443": {
                "class": "Application",
                "template": "https",
                "serviceMain": {
                    "pool": {
                        "use": "pl_vip1_80"
                    },
                    "snat": "auto",
                    "enable": true,
                    "iRules": [
                        {
                            "use": "iRule_vip1_443"
                        }
                    ],
                    "remark": "lekker hoor",
                    "serverTLS": "clssl_vip1",
                    "profileTCP": {
                        "use": "tcp_vip1_443"
                    },
                    "virtualPort": 443,
                    "profileHTTP": {
                        "use": "http_vip1_443"
                    },
                    "virtualAddresses": [
                        "10.10.10.1"
                    ],
                    "persistenceMethods": [
                        {
                            "use": "sticky-default_vip1"
                        }
                    ],
                    "fallbackPersistenceMethod": {
                        "use": "sticky-fallback_vip1"
                    },
                    "serviceDownImmediateAction": "drop",
                    "class": "Service_HTTPS"
                },
                "mon_vip1_80": {
                    "send": "GET / HTTP/1.0\r\n\r\n",
                    "receive": "",
                    "receiveDown": "",
                    "class": "Monitor",
                    "monitorType": "http"
                },
                "pl_vip1_80": {
                    "members": [
                        {
                            "adminState": "enable",
                            "servicePort": 80,
                            "serverAddresses": [
                                "192.168.4.10"
                            ]
                        }
                    ],
                    "monitors": [
                        {
                            "use": "mon_vip1_80"
                        }
                    ],
                    "class": "Pool"
                },
                "iRule_vip1_443": {
                    "iRule": {
                        "text": "when HTTP_REQUEST { log local0. \"test irule\" }"
                    },
                    "class": "iRule"
                },
                "sticky-default_vip1": {
                    "persistenceMethod": "cookie",
                    "class": "Persist"
                },
                "sticky-fallback_vip1": {
                    "persistenceMethod": "source-address",
                    "class": "Persist"
                },
                "clssl_vip1": {
                    "certificates": [
                        {
                            "certificate": "crt_vip1"
                        }
                    ],
                    "class": "TLS_Server"
                },
                "crt_vip1": {
                    "privateKey": {
                        "bigip": "/Common/default.key"
                    },
                    "certificate": {
                        "bigip": "/Common/default.crt"
                    },
                    "class": "Certificate"
                },
                "tcp_vip1_443": {
                    "class": "TCP_Profile"
                },
                "http_vip1_443": {
                    "class": "HTTP_Profile"
                }
            }
        }
    }
}
}
```

**Comment by trinaths** [comment]
@Zjemm I think in your AS3 JSON, `class` attribute is missing as per below error.

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "{'code': 422, 'message': 'status:422, body:{\"code\":422,\"message\":\"Invalid request value \\'[object Object]\\' (path: /declaration) : should have required property \\'class\\' {\\\\\"missingProperty\\\\\":\\\\\"class\\\\\"}\"}', 'originalRequestBody': '{\"code\":422,\"message\":\"Invalid request value \\'[object Object]\\' (path: /declaration) : should have required property \\'class\\' {\\\\\"missingProperty\\\\\":\\\\\"class\\\\\"}\"}', 'referer': '10.10.0.xxx', 'restOperationId': 57963195, 'errorStack': [], 'kind': ':resterrorresponse'}"}

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
