### ISSUE TITLE
Remove references to f5devcentral repository

### ISSUE THREAD

**Issue by mjmenger** [F5Networks/f5-ansible-bigip#17]
##### COMPONENT NAME

CloudDocs documentation

##### ANSIBLE VERSION

```
ansible [core 2.11.7] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```
##### BIGIP VERSION

```
N/A
```
##### CONFIGURATION

Installed v2 modules in local directory
collections_paths=./collections
##### SUMMARY

In the CloudDocs installation instructions for the v2 Ansible modules, there is a reference to use the f5devcentral repository if the user chooses to install from GitHub. Since the f5devcentral repository is out of date, this will result in invalid module path errors and similar.   
Suggested fixes:
 - The link in the documentation should be updated.
 - The f5devcentral repository for the v2 modules should be marked as archived

##### STEPS TO REPRODUCE

```
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/install_f5_bigip.html#install-from-github

ansible-galaxy collection install git+https://github.com/f5devcentral/f5-ansible-bigip.git#ansible_collections/f5networks/f5_bigip -p ./collections/
```

##### EXPECTED RESULTS

a complete installation of the v2 F5 Ansible modules
##### ACTUAL RESULTS

an incomplete installation of the v2 F5 Ansible modules

```

```

**Comment by trinaths** [comment]
Created [INFRAANO-668] for internal tracking.
