### ISSUE TITLE
Recursive loop with ansible_host variable

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible-bigip#34]
##### COMPONENT NAME
f5networks.f5_bigip.bigip_as3_deploy

##### ANSIBLE VERSION
```
ansible [core 2.12.2]
  config file = /home/cloud/ansible.cfg
  configured module search path = ['/home/cloud/plugins/modules']
  ansible python module location = /home/cloud/.venv/core212/lib/python3.8/site-packages/ansible
  ansible collection location = /home/cloud/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cloud/.venv/core212/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.3
  Build       0.21.11
  Edition     Engineering Hotfix
  Date        Wed Apr 28 09:38:30 PDT 2021

Hotfix List
ID940185-2    ID976505-2  ID755976-4  ID959629-2  ID981069-1  ID941625-1
ID1000973-3   ID746861-3  ID880289    ID975809-1  ID948717-3

```
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Referring to the Ansible built-in connection variable `ansible_host` in the required collection variable `ansible_host` causes playbook to fail with "recursive error".

##### STEPS TO REPRODUCE
```
---
- name: AS3
  hosts: "{{ targets }}"
  connection: httpapi
  gather_facts: false
  vars_files:
    - vault.yaml
  vars:
    ansible_host: "{{ ansible_host }}"
    ansible_user: admin
    ansible_httpapi_password: "{{ vault_password }}"
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Deploy or Update AS3
      f5networks.f5_bigip.bigip_as3_deploy:
          content: "{{ lookup('file', 'as3.json') }}"
```

##### EXPECTED RESULTS
Playbook should complete with no errors, as the playbook parameters are taken from the official collection documentation.

##### ACTUAL RESULTS
Playbook fails with "recursive error" caused by referring to the `ansible_host` variable.

```
TASK [Deploy or Update AS3] *************************************************************************************************************************************************************************************
Friday 12 August 2022  14:30:13 +0000 (0:00:00.162)       0:00:00.162 *********
fatal: [qa-de-1a-f512-02]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_host }}'.
<repeating output omitted>
```

**Comment by urohit011** [comment]
Hi @m-kratochvil , this error is occurring because in the vars section the variable `ansible_host` is referring to itself in the template string `"{{ ansible_host }}"`, change one of these and it should work fine, also could you give me the link of the documentation where you saw this example, so I could fix it.

**Comment by m-kratochvil** [comment]
Hi @urohit011 and thank you for checking. I got the example from the official docu here:
https://github.com/F5Networks/f5-ansible-bigip#tips
While in that example, it calls a variable `{{ provider.server }}`, I should always be able to call the ansible built-in `ansible_host` here, and so in my opinion to name the variable also `ansible_host` is unfortunate.

**Comment by urohit011** [comment]
I think it should be fine if you omit specifying the builtin variables provided they are being initialised with the correct value somewhere else.

**Comment by m-kratochvil** [comment]
I tested the playbook without explicitly setting the `ansible_host` (populated externally) and it works fine.
It was my misunderstanding of the documentation I mentioned above, which makes it look like it is mandatory to set the `ansible_host` in the playbook.

Thanks for the attention to this @urohit011 , you can close the issue.
