### ISSUE TITLE
bigip_sslo_config_ssl request - ability to control TLS processing options

### ISSUE THREAD

**Issue by kevingstewart** [F5Networks/f5-ansible-bigip#41]
##### COMPONENT NAME
bigip_sslo_config_ssl

##### SSL ORCHESTRATOR VERSION
```
All
```

### Is your feature request related to a problem? Please describe.
There is no way to control TLS processing options, to enable TLS1.3. This is expressed in the "enabledSSLProcessingOptions" array in the JSON.

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-929, thanks!

**Comment by KrithikaChidambaram** [comment]
Hi, it is included in the https://github.com/F5Networks/f5-ansible-bigip/releases/tag/1.12.0 release
