### ISSUE TITLE
as3_deploy: return result list

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible-bigip#59]
### Is your feature request related to a problem? Please describe.
Not really an issue but some "nice to have" information 

### Describe the solution you'd like
Using the module, in case of a successful as3 deploy, the as3 api returns a result object in a list  such as
[{'code': 200, 'message': 'success', 'lineCount': 23, 'host': 'localhost', 'tenant': 'APIm', 'runTime': 11466}]"
Please add it to the module output.

**Comment by pgouband** [comment]
Hi @amolari,

Could you give us more information why it should be interesting to add those output?

**Comment by pgouband** [comment]
Hi @amolari,

Unfortunately we have decided to not develop the RFE you made
