### ISSUE TITLE
bigip_config: merge_content expects file instead of str

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible-bigip#64]
##### COMPONENT NAME

`bigip_config` version 2.0.0

##### ANSIBLE VERSION

```
latest
```
##### BIGIP VERSION

```
16.1.3.4
```
##### SUMMARY

[bigip_config](https://github.com/F5Networks/f5-ansible-bigip/blob/devel/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_config.py) seems to expect a path to a file in the `merge_content` parameter. This is odd because a) the f5_modules.bigip_config `merge_content` parameter did expect a string and b) this does not allow to use jinja2 to define the actual configuration to be merged.
The parameter name also indicates it expects "content" instead of a path to a file on the filesystem.

The examples are broken but seem to inidicate a file has to be read by any ansible function turning it into "content" (str):

https://github.com/F5Networks/f5-ansible-bigip/blob/df5d60134cd8f280eb1ed78182b44b28f744f9be/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_config.py#L116-L129

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

The module parameter should accept str as input, similar to f5_modules.bigip_config

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
this was intentional change as the bigip_config changed. While we try to maintain 1:1 relation between imperative and declarative collection modules, these are not guaranteed to be interchangeable between imperative and declarative collections.
working as intended
