### ISSUE TITLE
Cannot view or modify SSLO security policy created by ansible module bigip_sslo_config_policy 

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-ansible-bigip#71]
### Cannot view or modify SSLO security policy created by ansible module bigip_sslo_config_policy 
After creating a SSLO policy using the ansible module bigip_sslo_config_policy, the resulting policy shows up in the SSLO GUI however you cannot view the rule conditions or modify them. 

### Describe the solution you'd like
Ability to view and modify the security policy rule conditionals created by this ansible module. All the other SSLO configuration items you can create with ansible modules (Services, Service Chain, SSL Configurations, etc...) you can still modify in the GUI in the event of an emergency change. 

### Additional context
Example GUI limitation of the ansible created security policy:
Warning banner:
![sslo-gui-hang](https://github.com/F5Networks/f5-ansible-bigip/assets/45299091/d2c9e64f-fde8-4ccc-906b-b273c6c5589d)
Rule overview shows conditionals: 
![2023-07-07_15-07-05](https://github.com/F5Networks/f5-ansible-bigip/assets/45299091/7109d793-8f3a-4ce2-a48a-28ac83abbceb)
After clicking edit, you cannot modify the conditionals: 
![2023-07-07_15-07-32](https://github.com/F5Networks/f5-ansible-bigip/assets/45299091/2abc9fc2-d099-480c-86ee-eaac3d7c17c2)

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1267.

**Comment by urohit011** [comment]
Hi @megamattzilla, I tried reproducing the issue but I am able to modify through the gui. Could you please provide the playbook which you're running. Also provide the SSLO version that you're using

**Comment by pgouband** [comment]
Hi @megamattzilla,

We didn't get any feedback from our last message so we are closing this issue.
Please reopen a new one if you are still facing the issue.
