### ISSUE TITLE
Secrets being distributed and caught by security scans.

### ISSUE THREAD

**Issue by sean-m-sullivan** [F5Networks/f5-ansible-bigip#77]
##### COMPONENT NAME
The following files are being flagged by security scans
RSA Private Key
collections/ansible_collections/f5networks/f5_bigip/tests/modules/network/f5/fixtures/cert1
Generic High Entropy Secret
collections/ansible_collections/f5networks/f5_bigip/tests/plugins/httpapi/test_bigiq.py

##### SUMMARY
The above files are being caught by security scans as containing some sensitive information. 

Would suggest the following two lines be added to galaxy.yml, which would ensure that future distributions do not include the test files so that the collection isn't flagged by security scans.
```
build_ignore:
  - tests
```

I am not sure how the CLA works between the Red Hat and F5, so decided to make this an issue instead of a PR to avoid any issues surrounding that. This should be a simple fix,

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1345.

**Comment by wojtek0806** [comment]
changes will be pushed next release

**Comment by sean-m-sullivan** [comment]
thanks!, this was driving clients security scanners nuts

**Comment by digitalfiend64** [comment]
> changes will be pushed next release

Thanks for getting the changes pushed out.  Do you happen to know what version should we expect this in?
